#!/bin/sh

request_block=$(cat request_block)
top_block=$(ledger-top)
random_seed=$(ledger-read $top_block)
args=($random_seed)

seed=${args[1]}

echo "[Peer B] creating random subsection proof of document.txt"
subsection_proof=$(kzg-cli prove document.txt $seed)
args=($subsection_proof)

proof=${args[0]}
data=${args[1]}

published_block=$(ledger-top)
published_block=$((published_block+1))
echo "[Peer B] publishing subsection proof along with data"
ledger-publish file_proof $request_block $proof $data
echo $published_block >> proof_of_host
