#!/bin/bash

cd $SHARED_FOLDER

if ! [ -d ledger ]; then
  mkdir -p ledger
fi

if ! [ -f ledger/0 ]; then
  echo "genesis" > ledger/0
fi

cd ledger

next_block=0
for file in *; do
  block_num=$((file-"0"+1))
  if [ $block_num -gt $next_block ]; then
    next_block=$block_num
  fi
done

echo "$*" > $next_block
echo "published block #$next_block: '$*'"
